# Model configuration
gnn:
  input_dim: 6
  hidden_dim: 64
  num_layers: 1
  num_embeddings: 4
  embedding_size: 8
  edge_dim: 1
  use_attention: true

actor:
  obs_dim: 9  # waypoint 포함한 실제 차원
  agg_dim: 64
  action_dim: 4
  hidden_dim: 64

critic:
  agg_dim: 64
  hidden_dim: 64