# Training configuration
training:
  num_episodes: 5  # 테스트용
  learning_rate: 0.001
  batch_size: 96
  ppo_epochs: 2
  
  # 하드코딩된 값들을 YAML로 이동
  update_frequency: 25  # 실제 사용 값
  
  # PPO parameters (하드코딩에서 이동)
  clip_epsilon: 0.2
  
  # GAE parameters (하드코딩에서 이동)
  gamma: 0.99
  lambda: 0.95
  
  # Loss weights (하드코딩에서 이동)
  value_loss_coef: 0.5
  entropy_coef: 0.01
  
  # Gradient clipping (하드코딩에서 이동)
  max_grad_norm: 0.5
  
  # Evaluation (하드코딩에서 이동)
  eval_frequency: 5  # 실제 사용 값